version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install
      - run:
          name: run unit test
          command: |
            npm run test
      - store_test_results:
          path: test_report
      - store_artifacts:
          path: test_report
workflows:
  build_test:
    jobs:
      - run_tests